language: generic
os: osx
osx_image: xcode7.3
#osx_image: xcode9.4
before_script:
 - bash ./install.sh


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
